<?php

namespace AppBundle\Repository;

/**
 * Products_CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Products_CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
