AppBundle\Entity\Products:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 255
            unique: true
        name:
            type: string
            length: 255
            unique: true
        description:
            type: string
            length: 255
        mark:
            type: string
            length: 255
        price:
            type: float
    lifecycleCallbacks: {  }
